export {
  DEFAULT_CONTEXT_SELECTION_LIMITS,
  CONTEXT_MANIFEST_SCHEMA_VERSION,
  REPOSITORY_PREFLIGHT_SCHEMA_VERSION,
  containsDisallowedSecretOrEnvironmentValue,
  isDeniedRepositoryRelativePath,
  pathIsWithin,
  resolveRepositoryPreflight,
  selectMigrateToViteContext,
  type ContextExclusionReason,
  type ContextInclusionReason,
  type ContextManifestExclusion,
  type ContextManifestFile,
  type ContextSelectionLimits,
  type RepositoryContextBundle,
  type RepositoryContextDocument,
  type RepositoryContextManifest,
  type RepositoryPreflight,
} from "./repository-context.js";
export {
  detectViteApplicability,
  type ApplicabilityEvidence,
  type ApplicabilityEvidenceKind,
  type ViteApplicability,
  type ViteApplicabilityStatus,
} from "./vite-applicability.js";
export {
  MIGRATE_TO_VITE_PREFLIGHT_SCHEMA_VERSION,
  assertMigrateToVitePreflightIntegrity,
  prepareMigrateToVitePreflight,
  type MigrateToVitePreflight,
  type SelectedSkillInput,
  type SelectedSkillSnapshot,
} from "./preflight.js";
export {
  MIGRATE_TO_VITE_PLAN_SCHEMA_VERSION,
  MIGRATE_TO_VITE_PLAN_V1_SCHEMA,
  PlanValidationError,
  buildMigrateToVitePlanPrompt,
  parseMigrateToVitePlanV1,
  renderMigrateToVitePlanMarkdown,
  validateMigrateToVitePlanV1,
  type ChangeAction,
  type CleanupCandidate,
  type DependencyChange,
  type MigrateToVitePlanV1,
  type PackageManager,
  type ParityChecklistItem,
  type ParityDisposition,
  type PlanEvidenceReference,
  type PlannedChange,
  type PlannedVerification,
  type ProjectType,
  type ScriptChange,
} from "./migrate-to-vite-plan.js";
export {
  writePlanningRunMetadata,
  writeMigrateToVitePlanArtifacts,
  type PlanningArtifactFile,
  type PlanningArtifactPaths,
} from "./artifact-store.js";
